### ISSUE TITLE
HEIC conversion failed

### ISSUE THREAD

**Issue by w67360-si2** [iib0011/omni-tools#253]
The tool to convert image file to JPG pretends to convert from HEIC:
> Convert Images to JPG
> Convert various image formats (PNG, GIF, TIF, PSD, SVG, WEBP, **HEIC**, RAW) to JPG with customizable quality and background color settings.
 
But it failed, at least in my case:
```
Error processing image: DOMException: Invalid encoded image data. index-CqVDdwXY.js:1:22082
    C https://omnitools.wissembourg.fr/assets/index-CqVDdwXY.js:1
    C https://omnitools.wissembourg.fr/assets/index-CqVDdwXY.js:1
    Eu https://omnitools.wissembourg.fr/assets/ToolContent-lOGc3QP4.js:1
    Kl https://omnitools.wissembourg.fr/assets/index-BRkQvE4N.js:41
    Mo https://omnitools.wissembourg.fr/assets/index-BRkQvE4N.js:41
    qw https://omnitools.wissembourg.fr/assets/index-BRkQvE4N.js:41
    Er https://omnitools.wissembourg.fr/assets/index-BRkQvE4N.js:41
    Eh https://omnitools.wissembourg.fr/assets/index-BRkQvE4N.js:41
    xr https://omnitools.wissembourg.fr/assets/index-BRkQvE4N.js:39
    Hr https://omnitools.wissembourg.fr/assets/index-BRkQvE4N.js:41
    gy https://omnitools.wissembourg.fr/assets/index-BRkQvE4N.js:38
    bc https://omnitools.wissembourg.fr/assets/index-BRkQvE4N.js:38
    Vf https://omnitools.wissembourg.fr/assets/index-BRkQvE4N.js:38
    IS https://omnitools.wissembourg.fr/assets/index-BRkQvE4N.js:38
```

[Original image file attached](https://github.com/user-attachments/assets/92298001-eb87-4cd5-98ea-13f0e2955149)

**Comment by o-200** [comment]
Hey, i'd like to work with that.

I see that the original image is incorrect. Seems that Github converted it to jpg. 

Bug is reproduced [with that heic image](https://github.com/tigranbs/test-heic-images/blob/master/image4.heic).

**Comment by SickProdigy** [comment]
Also having an issue. Taking iphone image HEIC and trying to convert to jpg

**Comment by skurty** [comment]
Same issue here with an iPhone HEIC image.

**Comment by rsh015** [comment]
Same. Unable to convert from HEIC to JPG

**Comment by Chesterkxng** [comment]
Hey everyone! Sorry for the delay — I’ve pushed a fix. Could you take a look and let me know if it works on your side?

Note: input file loading may take a bit longer for HEIC images. 
@skurty @rsh015 @SickProdigy @o-200

**Comment by o-200** [comment]
> Hey everyone! Sorry for the delay — I’ve pushed a fix. Could you take a look and let me know if it works on your side?
> 
> Note: input file loading may take a bit longer for HEIC images. [@skurty](https://github.com/skurty) [@rsh015](https://github.com/rsh015) [@SickProdigy](https://github.com/SickProdigy) [@o-200](https://github.com/o-200)

Seems like it works! Nice to see that fixed

**Comment by skurty** [comment]
It works but I don't have the translations, only the keys: `convertToJPG.title`, `convertToJPG.description`...

**Comment by Chesterkxng** [comment]
Refresh the page to see if it doesn't fix it !

**Comment by skurty** [comment]
Unfortunately, it still doesn't work and it's the only page with this translation issue. I tried several languages with the same result.

**Comment by Chesterkxng** [comment]
Try clearing your browser cache! I tried it on several browsers, and it worked.
<img width="2273" height="1268" alt="Image" src="https://github.com/user-attachments/assets/81f1703a-c4cc-4b9c-9cbc-c1a84e7d0424" />

**Comment by skurty** [comment]
I disabled the cache in the dev tools network and it worked, thank you!

**Comment by SickProdigy** [comment]
looks like it's working on my end also! Thanks for the update!
